version: "3"
services:
  ptv-mongo:
    image: mongo:4.4
    container_name: ptv-mongo
    ports:
      - 27017:27017
    networks:
      - ptvdm
    volumes:
      - mongodump:/data/db
    restart: always

  ptv-dm:
    image: node:16-stretch
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_SUB_HOST: ${REDIS_HOST}
      REDIS_SUB_PORT: ${REDIS_PORT}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PUB_HOST: ${REDIS_HOST}
      REDIS_PUB_PORT: ${REDIS_PORT}
      MONGO_DB_HOST: ${MONGO_DB_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_DB: ${MONGO_DB}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASS: ${MYSQL_PASSWORD}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_DB: "picarto_dev"
      REDIS_SUB_PREFIX: ptv_dev_
      REDIS_PUB_PREFIX: ptv_dev_
      REDIS_PREFIX: ptv_dev_
    working_dir: /app
    command: npm start
    container_name: ptv-dm
    volumes:
      - ./:/app
    restart: always

    networks:
      - ptvdm
      - webapp
    labels:
      - traefik.backend=ptv-dm
      - traefik.normal.frontend.rule=Host:ptvdm-dev.diagonal.solutions
      - traefik.docker.network=webapp
      - traefik.port=9001

volumes:
  mongodump:

networks:
  ptvdm:
  webapp:
    external: true
